<?php
$judul=mysql_escape_string($_POST[judul]);
$link=mysql_escape_string($_POST[link]);
$fileres=$_FILES[fileres][name];
$tmp_file=$_FILES[fileres][tmp_name];
$category=mysql_escape_string($_POST[category]);
$author=mysql_escape_string($_POST[author]);
$isi=mysql_escape_string($_POST[isi]);
$status=mysql_escape_string($_POST[status]);
$harga=mysql_escape_string($_POST[harga]);
$filefoto=$_FILES[filefoto][name];
$tmp_foto=$_FILES[filefoto][tmp_name];
$tanggal=date('d-F-Y');
$fname=mysql_escape_string($_POST[fname]);
$lname=mysql_escape_string($_POST[lname]);
$province=mysql_escape_string($_POST[province]);
$city=mysql_escape_string($_POST[city]);
$address=mysql_escape_string($_POST[address]);
$phone=mysql_escape_string($_POST[phone]);
$gelar=mysql_escape_string($_POST[gelar]);
$description=mysql_escape_string($_POST[description]);
$username=mysql_escape_string($_POST[username]);
$password=md5(mysql_escape_string($_POST[password]));
?>